project_id = "mokhssmnorrhohrowxvu"

[functions.realtime-voice-tournament]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.configure-telegram-bot]
verify_jwt = false

[functions.send-clan-notification]
verify_jwt = false

[functions.tournament-level-manager]
verify_jwt = false

[functions.tournament-table-balancer]
verify_jwt = false
