tunnel: a09c9140-45fc-4cbe-9b2f-e5df95d37b46
credentials-file: /root/.cloudflared/a09c9140-45fc-4cbe-9b2f-e5df95d37b46.json

ingress:
  # Главный фронтенд домен
  - hostname: syndicate-poker.ru
    service: https://a391e581-510e-4cfc-905a-60ff6b51b1e6.lovableproject.com
    originRequest:
      noTLSVerify: true
  
  # WWW редирект на основной домен
  - hostname: www.syndicate-poker.ru
    service: https://a391e581-510e-4cfc-905a-60ff6b51b1e6.lovableproject.com
    originRequest:
      noTLSVerify: true
  
  # Catch-all правило (обязательно)
  - service: http_status:404
